apiVersion: v1
kind: Service
metadata:
  name: kubewatch-service
spec:
  selector:
    app: kubewatch

  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.targetPort }}

  type: {{ .Values.api.service.type }}
