apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kubewatch-api
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: kubewatch
  endpoints:
    - port: http
      path: /metrics/
      interval: 15s
